language: java
sudo: false

before_install:
      - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
    include:
    # Java 10 "OpenJDK"
  - env: JDK='OpenJDK 10'
    install: . ./install-jdk.sh -F 10 -L GPL

env:
  - TEST_DIR=Lazy
  - TEST_DIR=ftp-server

script: 
    cd $TEST_DIR && ./gradlew clean check
